name: Test, Integration Tests and Deploy

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  schedule:
  - cron: '0 8 * * *'
jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: set matrix
        id: set-matrix
        env:
          REF: ${{ github.ref }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          if [ "$REF" == "refs/heads/$DEFAULT_BRANCH" ] || [[ "$REF" =~ ^refs/tags/.* ]]
          then
              echo "::set-output name=matrix::{\"python-version\": [\"3.7\", \"3.10\"]}"
          else
              echo "::set-output name=matrix::{\"python-version\": [\"3.9\"]}"
          fi
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Check style
        run: |
          pydocstyle renkumls
          black --check --diff renkumls tests
          isort -c --df .
          flake8 renkumls/
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run Tests
        run: |
          pytest -v -o testpaths="tests"